# Generated by Django 3.2 on 2022-10-26 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='IdNumber',
            field=models.CharField(max_length=30, null=True, verbose_name='IdNumber'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Modalities',
            field=models.CharField(choices=[(None, ' modalities'), ('CT', 'CT'), ('US', 'US'), ('MRI', 'MRI'), ('Mammogram', 'Mammogram')], max_length=30, null=True, verbose_name='Modalities'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Nationality',
            field=models.CharField(choices=[(None, 'Nationality'), ('Suadi', 'Suadi'), ('Non Suadi', 'Non Suadi')], max_length=10, null=True, verbose_name='Nationalty'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Other_study',
            field=models.CharField(max_length=30, null=True, verbose_name=' Other_study'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Side_label',
            field=models.CharField(choices=[(None, 'Side_label'), ('right', 'right'), ('left', 'left'), ('all', 'all')], max_length=30, null=True, verbose_name='Side_label '),
        ),
        migrations.AddField(
            model_name='patient',
            name='Study_part',
            field=models.CharField(choices=[(None, 'Study_part'), ('Abdomen', 'Abdomen'), ('KUB', 'KUB'), ('OB less than 14 Weeks', 'OB less than 14 Weeks '), ('OB  more than 14 Weeks', 'OB more than 14 Weeks '), ('Brain', 'Brain'), ('Neck', 'Neck'), ('Chest', 'Chest'), ('pelvis', 'pelvis'), ('pan-CT', 'pan-CT'), ('thyroid', 'thyroid'), ('breast', 'breast'), ('scrotal', 'scrotal'), ('cervical spine', 'cervical spine'), ('L/S spine', 'L/S spine'), ('D/L spine', 'D/L spine'), ('doppler-venous-lower', 'doppler-venous-lower'), ('doppler-arterial-lower', 'doppler-arterial-lower'), ('doppler-venous-upper', 'doppler-venous-upper'), ('doppler-arterial-upper', 'doppler-arterial-upper'), ('all spine', 'all spine'), ('Shoulder', 'Shoulder'), ('elbow', 'elbow'), ('wrist&hand', 'wrist&hand'), ('hip', 'hip'), ('knee', 'knee'), ('ankle&foot', 'ankle&foot'), ('superficial-MSK', 'superficial-MSK')], max_length=30, null=True, verbose_name='Study_part'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Unit_name',
            field=models.CharField(choices=[(None, 'Unit_name'), ('ER', 'ER'), ('pedia_ward', 'pedia_ward'), ('male_ward', 'male_ward'), ('female_ward', 'female_ward'), ('OB_ward', 'OB_ward'), ('L&D_ward', 'L&D_ward'), ('covid_ward', 'covid_ward'), ('OPD', 'OPD'), ('refferal', 'referral')], max_length=30, null=True, verbose_name='Unit_name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=30, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_indication',
            field=models.CharField(max_length=300, null=True, verbose_name=' clinical_indication '),
        ),
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='departments',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], max_length=30, null=True, verbose_name='departments'),
        ),
        migrations.AddField(
            model_name='patient',
            name='flag',
            field=models.CharField(choices=[(None, 'STATUS_FLAG'), ('Top_Emergency', 'Top_Emergency'), ('Emergency', 'Emergency'), ('Routine', 'Routine')], max_length=30, null=True, verbose_name='Flag'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[(None, 'gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='patient',
            name='provisional_diagnosis',
            field=models.CharField(max_length=100, null=True, verbose_name=' provisional_diagnosis '),
        ),
        migrations.AddField(
            model_name='patient',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
